name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        ruby-version: ['3.2', '3.3', '3.4']

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Install build tools on macOS
        if: runner.os == 'macOS'
        run: brew install automake libtool

      - name: Install dependencies
        run: bundle install

      - name: Build secp256k1
        run: ./make.sh

      - name: Run tests
        run: ./test.sh

      - name: Build gem
        run: gem build --output=release.gem
